/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_VentanaPrincipal;

/**
 *
 * @author RandyGUTI
 */
public class Panel_Informacion extends javax.swing.JPanel {

    Controlador_FRM_VentanaPrincipal controlador;
    
    public Panel_Informacion() {
        initComponents();
    }
    public void agregarEventos(Controlador_FRM_VentanaPrincipal controlador)
    {
      this.controlador=controlador;
      this.btn_ConsultaRapida.addActionListener(controlador);
      this.jt_NumeroPrestamo.addActionListener(controlador);
    }
    public String devolverNumeroPrestamo()
    {
      return jt_NumeroPrestamo.getText();
    }
    public void colocarNumeroPrestamo(String numero)
    {
      this.jt_NumeroPrestamo.setText(numero);
    }
    public void habilitarCampos()
    {
      this.jt_Nombre.setEnabled(true);
      this.jt_Cedula.setEnabled(true);
      this.jt_ISBN_Libro.setEnabled(true);
    }
    public void deshabilitarCampos()
    {
      this.jt_Nombre.setEnabled(false);
      this.jt_Cedula.setEnabled(false);
      this.jt_ISBN_Libro.setEnabled(false);
      this.jt_Nombre.setText("");
      this.jt_Cedula.setText("");
      this.jt_ISBN_Libro.setText("");
    }
    public void mostrarInformacion(String arreglo[])
    {
      this.jt_Nombre.setText(arreglo[0]);
      this.jt_Cedula.setText(arreglo[1]);
      this.jt_ISBN_Libro.setText(arreglo[2]);
    }
    public String[] devolverInformacion()
    {
      String arreglo[]=new String[4];
      arreglo[0]=this.jt_NumeroPrestamo.getText();
      arreglo[1]=this.jt_Nombre.getText();
      arreglo[2]=this.jt_Cedula.getText();
      arreglo[3]=this.jt_ISBN_Libro.getText();
      
      return arreglo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NumeroPrestamo = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_ISBN_Libro = new javax.swing.JLabel();
        jt_NumeroPrestamo = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Cedula = new javax.swing.JTextField();
        jt_ISBN_Libro = new javax.swing.JTextField();
        btn_ConsultaRapida = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jl_NumeroPrestamo.setText("Número de Préstamo");

        jl_Nombre.setText("Nombre del Usuario");

        jl_Cedula.setText("Cédula del Usuario");

        jl_ISBN_Libro.setText("ISBN del Libro");

        jt_NumeroPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_NumeroPrestamoKeyPressed(evt);
            }
        });

        jt_Nombre.setEnabled(false);

        jt_Cedula.setEnabled(false);

        jt_ISBN_Libro.setEnabled(false);

        btn_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_ConsultaRapida.setActionCommand("ConsultaRapida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_NumeroPrestamo)
                    .addComponent(jl_Nombre)
                    .addComponent(jl_Cedula)
                    .addComponent(jl_ISBN_Libro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_NumeroPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jt_ISBN_Libro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jt_Nombre)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addComponent(btn_ConsultaRapida)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_NumeroPrestamo)
                            .addComponent(jt_NumeroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_ConsultaRapida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cedula)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ISBN_Libro)
                    .addComponent(jt_ISBN_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NumeroPrestamoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NumeroPrestamoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10)
        {
          controlador.consultar();
        }
    }//GEN-LAST:event_jt_NumeroPrestamoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ConsultaRapida;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_ISBN_Libro;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_NumeroPrestamo;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_ISBN_Libro;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_NumeroPrestamo;
    // End of variables declaration//GEN-END:variables
}
